Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job stats:
job           count    min threads    max threads
----------  -------  -------------  -------------
evaluation        1              1              1
total             1              1              1

Resources before job selection: {'_cores': 1, '_nodes': 9223372036854775807}
Ready jobs (1):
	evaluation
Select jobs to execute...
Selected jobs (1):
	evaluation
Resources after job selection: {'_cores': 0, '_nodes': 9223372036854775806}

[Mon Jul  5 16:09:37 2021]
rule evaluation:
    input: data/gene_data.csv, data/AllLabels.csv, ml/LR_l1.joblib
    output: results/LR_l1.csv
    jobid: 0
    wildcards: method=LR_l1
    resources: tmpdir=/tmp

Full Traceback (most recent call last):
  File "/home/fernando/mambaforge/envs/snakemake-tutorial-ml/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2372, in run_wrapper
    run(
  File "/mnt/c/Users/Fernando/Documents/MRes Biomedical Research/Project 2/Github/BenchmarkDR/workflow/rules/prediction/Snakefile", line 79, in __rule_evaluation
  File "/home/fernando/mambaforge/envs/snakemake-tutorial-ml/lib/python3.8/site-packages/snakemake/shell.py", line 263, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python scripts/evaluation.py --data data/gene_data.csv --label data/AllLabels.csv --config models_conf.yml --model ml/LR_l1.joblib --model-name LR_l1 --optimize RandomizedSearchCV' returned non-zero exit status 1.

[Mon Jul  5 16:09:37 2021]
Error in rule evaluation:
    jobid: 0
    output: results/LR_l1.csv
    shell:
        python scripts/evaluation.py --data data/gene_data.csv --label data/AllLabels.csv --config models_conf.yml --model ml/LR_l1.joblib --model-name LR_l1 --optimize RandomizedSearchCV
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/home/fernando/mambaforge/envs/snakemake-tutorial-ml/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2372, in run_wrapper
    run(
  File "/mnt/c/Users/Fernando/Documents/MRes Biomedical Research/Project 2/Github/BenchmarkDR/workflow/rules/prediction/Snakefile", line 79, in __rule_evaluation
  File "/home/fernando/mambaforge/envs/snakemake-tutorial-ml/lib/python3.8/site-packages/snakemake/shell.py", line 263, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python scripts/evaluation.py --data data/gene_data.csv --label data/AllLabels.csv --config models_conf.yml --model ml/LR_l1.joblib --model-name LR_l1 --optimize RandomizedSearchCV' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fernando/mambaforge/envs/snakemake-tutorial-ml/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 592, in _callback
    raise ex
  File "/home/fernando/mambaforge/envs/snakemake-tutorial-ml/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/fernando/mambaforge/envs/snakemake-tutorial-ml/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 578, in cached_or_run
    run_func(*args)
  File "/home/fernando/mambaforge/envs/snakemake-tutorial-ml/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2405, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 39 of /mnt/c/Users/Fernando/Documents/MRes Biomedical Research/Project 2/Github/BenchmarkDR/workflow/rules/prediction/Snakefile:
Command 'python scripts/evaluation.py --data data/gene_data.csv --label data/AllLabels.csv --config models_conf.yml --model ml/LR_l1.joblib --model-name LR_l1 --optimize RandomizedSearchCV' returned non-zero exit status 1.
  File "/mnt/c/Users/Fernando/Documents/MRes Biomedical Research/Project 2/Github/BenchmarkDR/workflow/rules/prediction/Snakefile", line 39, in __rule_evaluation

RuleException:
CalledProcessError in line 39 of /mnt/c/Users/Fernando/Documents/MRes Biomedical Research/Project 2/Github/BenchmarkDR/workflow/rules/prediction/Snakefile:
Command 'python scripts/evaluation.py --data data/gene_data.csv --label data/AllLabels.csv --config models_conf.yml --model ml/LR_l1.joblib --model-name LR_l1 --optimize RandomizedSearchCV' returned non-zero exit status 1.
  File "/mnt/c/Users/Fernando/Documents/MRes Biomedical Research/Project 2/Github/BenchmarkDR/workflow/rules/prediction/Snakefile", line 39, in __rule_evaluation
  File "/home/fernando/mambaforge/envs/snakemake-tutorial-ml/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /mnt/c/Users/Fernando/Documents/MRes Biomedical Research/Project 2/Github/BenchmarkDR/workflow/rules/prediction/.snakemake/log/2021-07-05T160937.471956.snakemake.log
unlocking
removing lock
removing lock
removed all locks
