Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job stats:
job           count    min threads    max threads
----------  -------  -------------  -------------
evaluation        1              1              1
total             1              1              1

Resources before job selection: {'_cores': 9223372036854775807, '_nodes': 1}
Ready jobs (1):
	evaluation
Select jobs to execute...
Selected jobs (1):
	evaluation
Resources after job selection: {'_cores': 9223372036854775806, '_nodes': 0}

[Fri Jun 25 13:59:40 2021]
rule evaluation:
    input: data/gene_data.csv, data/AllLabels.csv, ml/LR_l1.joblib
    output: results/LR_l1.txt
    jobid: 0
    wildcards: method=LR_l1
    resources: tmpdir=/tmp

Full Traceback (most recent call last):
  File "/home/fernando/mambaforge/envs/snakemake-tutorial-ml/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2372, in run_wrapper
    run(
  File "/mnt/c/Users/Fernando/Documents/MRes Biomedical Research/Project 2/Github/BenchmarkDR/workflow/rules/prediction/Snakefile", line 74, in __rule_evaluation
  File "/home/fernando/mambaforge/envs/snakemake-tutorial-ml/lib/python3.8/site-packages/snakemake/shell.py", line 263, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python scripts/evaluation.py -d data/gene_data.csv -l data/AllLabels.csv -m ml/LR_l1.joblib' returned non-zero exit status 1.

[Fri Jun 25 13:59:49 2021]
Error in rule evaluation:
    jobid: 0
    output: results/LR_l1.txt
    shell:
        python scripts/evaluation.py -d data/gene_data.csv -l data/AllLabels.csv -m ml/LR_l1.joblib
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/home/fernando/mambaforge/envs/snakemake-tutorial-ml/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2372, in run_wrapper
    run(
  File "/mnt/c/Users/Fernando/Documents/MRes Biomedical Research/Project 2/Github/BenchmarkDR/workflow/rules/prediction/Snakefile", line 74, in __rule_evaluation
  File "/home/fernando/mambaforge/envs/snakemake-tutorial-ml/lib/python3.8/site-packages/snakemake/shell.py", line 263, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python scripts/evaluation.py -d data/gene_data.csv -l data/AllLabels.csv -m ml/LR_l1.joblib' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fernando/mambaforge/envs/snakemake-tutorial-ml/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 592, in _callback
    raise ex
  File "/home/fernando/mambaforge/envs/snakemake-tutorial-ml/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/fernando/mambaforge/envs/snakemake-tutorial-ml/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 578, in cached_or_run
    run_func(*args)
  File "/home/fernando/mambaforge/envs/snakemake-tutorial-ml/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2405, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in line 36 of /mnt/c/Users/Fernando/Documents/MRes Biomedical Research/Project 2/Github/BenchmarkDR/workflow/rules/prediction/Snakefile:
Command 'python scripts/evaluation.py -d data/gene_data.csv -l data/AllLabels.csv -m ml/LR_l1.joblib' returned non-zero exit status 1.
  File "/home/fernando/mambaforge/envs/snakemake-tutorial-ml/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2372, in run_wrapper
  File "/mnt/c/Users/Fernando/Documents/MRes Biomedical Research/Project 2/Github/BenchmarkDR/workflow/rules/prediction/Snakefile", line 36, in __rule_evaluation

RuleException:
CalledProcessError in line 36 of /mnt/c/Users/Fernando/Documents/MRes Biomedical Research/Project 2/Github/BenchmarkDR/workflow/rules/prediction/Snakefile:
Command 'python scripts/evaluation.py -d data/gene_data.csv -l data/AllLabels.csv -m ml/LR_l1.joblib' returned non-zero exit status 1.
  File "/home/fernando/mambaforge/envs/snakemake-tutorial-ml/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2372, in run_wrapper
  File "/mnt/c/Users/Fernando/Documents/MRes Biomedical Research/Project 2/Github/BenchmarkDR/workflow/rules/prediction/Snakefile", line 36, in __rule_evaluation
  File "/home/fernando/mambaforge/envs/snakemake-tutorial-ml/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 592, in _callback
  File "/home/fernando/mambaforge/envs/snakemake-tutorial-ml/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/home/fernando/mambaforge/envs/snakemake-tutorial-ml/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 578, in cached_or_run
  File "/home/fernando/mambaforge/envs/snakemake-tutorial-ml/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2405, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /mnt/c/Users/Fernando/Documents/MRes Biomedical Research/Project 2/Github/BenchmarkDR/workflow/rules/prediction/.snakemake/log/2021-06-25T135939.669587.snakemake.log
unlocking
removing lock
removing lock
removed all locks
